"""
Phase 4 - Step 1: Build NEXUS Presence/Absence Matrix
======================================================
Reads hybrid_cognates.csv and constructs a binary character matrix:
  rows    = language taxa
  columns = cognate set IDs (characters)
  values  = 1 if that language has a member in that cognate set, else 0

Output: output/turkic_cognates.nex  (NEXUS format for BEAST/MrBayes)
        output/nexus_summary.txt    (character count, taxon list)

Notes:
- Cognate IDs starting with 1000xx are LexStat-only sets. These are
  included but flagged in the summary so BEAST operators can assess
  their weight.
- Missing data (?): a language may lack coverage for a gloss entirely.
  We distinguish 0 (different cognate set present) from ? (no data).
"""

import pandas as pd
from pathlib import Path

ROOT   = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "output"


def load_data():
    df = pd.read_csv(OUTPUT / "hybrid_cognates.csv")
    return df


def build_matrix(df):
    """
    Returns:
        taxa       : list of language names (sorted)
        char_ids   : list of cognate IDs used as characters (sorted)
        matrix     : dict {taxon: dict {char_id: '0'|'1'|'?'}}
        glosses_per_cog : dict {cogid: gloss}  (for annotation)
    """
    taxa = sorted(df["language"].unique().tolist())
    char_ids = sorted(df["cogid"].unique().tolist())

    # Map cogid -> representative gloss
    glosses_per_cog = (
        df.groupby("cogid")["gloss"].first().to_dict()
    )

    # For each language, which glosses are present?
    lang_glosses = {}
    for lang, grp in df.groupby("language"):
        lang_glosses[lang] = set(grp["gloss"].tolist())

    # All glosses observed in the full dataset
    all_glosses = set(df["gloss"].unique())

    # Build matrix
    matrix = {t: {} for t in taxa}
    for cog_id in char_ids:
        gloss = glosses_per_cog[cog_id]
        # Which taxa have this specific cognate?
        with_cog = set(df[df["cogid"] == cog_id]["language"].tolist())
        for t in taxa:
            if t not in lang_glosses or gloss not in lang_glosses[t]:
                # Language has no entry for this gloss at all
                matrix[t][cog_id] = "?"
            elif t in with_cog:
                matrix[t][cog_id] = "1"
            else:
                matrix[t][cog_id] = "0"

    return taxa, char_ids, matrix, glosses_per_cog


def write_nexus(taxa, char_ids, matrix, glosses_per_cog, outpath):
    """
    Write a NEXUS file with a CHARACTERS block using standard format
    compatible with BEAST 2 and MrBayes.
    """
    ntax  = len(taxa)
    nchar = len(char_ids)
    max_name = max(len(t) for t in taxa)
    pad = max_name + 2

    lines = []
    lines.append("#NEXUS\n")
    lines.append("[Turkic cognate presence/absence matrix - Phase 4]\n")
    lines.append("[Generated by build_nexus.py]\n")
    lines.append("[Characters are LexStat/Savelyev cognate set IDs]\n")
    lines.append("\n")

    # TAXA block
    lines.append("BEGIN TAXA;\n")
    lines.append(f"\tDIMENSIONS NTAX={ntax};\n")
    lines.append("\tTAXLABELS\n")
    for t in taxa:
        lines.append(f"\t\t{t}\n")
    lines.append("\t;\n")
    lines.append("END;\n\n")

    # CHARACTERS block
    lines.append("BEGIN CHARACTERS;\n")
    lines.append(f"\tDIMENSIONS NCHAR={nchar};\n")
    lines.append("\tFORMAT DATATYPE=RESTRICTION MISSING=? GAP=- SYMBOLS=\"01\";\n")
    lines.append("\tCHARLABELS\n")
    for i, cid in enumerate(char_ids):
        gloss = glosses_per_cog[cid]
        is_lexstat = "LS" if cid >= 100000 else "SV"
        lines.append(f"\t\t[{i+1}] cog{cid}_{gloss}_{is_lexstat}\n")
    lines.append("\t;\n")
    lines.append("\tMATRIX\n")
    for t in taxa:
        seq = "".join(matrix[t][c] for c in char_ids)
        lines.append(f"\t\t{t:<{pad}} {seq}\n")
    lines.append("\t;\n")
    lines.append("END;\n\n")

    # Assumptions block: note LexStat characters
    lexstat_chars = [i+1 for i, c in enumerate(char_ids) if c >= 100000]
    if lexstat_chars:
        lines.append("BEGIN ASSUMPTIONS;\n")
        lines.append("\t[LexStat-only characters (less Savelyev grounding):]\n")
        char_list = " ".join(str(x) for x in lexstat_chars)
        lines.append(f"\t[CHARSET LexStat = {char_list};]\n")
        lines.append("END;\n\n")

    with open(outpath, "w", encoding="utf-8") as f:
        f.writelines(lines)


def write_summary(taxa, char_ids, matrix, glosses_per_cog, outpath):
    lexstat_chars = [c for c in char_ids if c >= 100000]
    savelyev_chars = [c for c in char_ids if c < 100000]

    missing_counts = {}
    for t in taxa:
        missing_counts[t] = sum(1 for c in char_ids if matrix[t][c] == "?")

    lines = []
    lines.append("NEXUS MATRIX SUMMARY\n")
    lines.append("=" * 50 + "\n")
    lines.append(f"Taxa (languages):         {len(taxa)}\n")
    lines.append(f"Characters (cognate sets): {len(char_ids)}\n")
    lines.append(f"  Savelyev-grounded:        {len(savelyev_chars)}\n")
    lines.append(f"  LexStat-only:             {len(lexstat_chars)}\n\n")
    lines.append("Missing data per taxon (? entries):\n")
    for t in taxa:
        pct = 100 * missing_counts[t] / len(char_ids)
        lines.append(f"  {t:<18} {missing_counts[t]:3d} / {len(char_ids)}  ({pct:.1f}%)\n")
    lines.append("\nGloss coverage per character group:\n")
    gloss_cog_counts = {}
    for c in char_ids:
        g = glosses_per_cog[c]
        gloss_cog_counts[g] = gloss_cog_counts.get(g, 0) + 1
    for g, cnt in sorted(gloss_cog_counts.items(), key=lambda x: -x[1]):
        lines.append(f"  {g:<20} {cnt} cognate set(s)\n")

    with open(outpath, "w", encoding="utf-8") as f:
        f.writelines(lines)


def main():
    print("Loading hybrid_cognates.csv...")
    df = load_data()

    print("Building presence/absence matrix...")
    taxa, char_ids, matrix, glosses_per_cog = build_matrix(df)

    nexus_path   = OUTPUT / "turkic_cognates.nex"
    summary_path = OUTPUT / "nexus_summary.txt"

    print(f"Writing NEXUS file: {nexus_path}")
    write_nexus(taxa, char_ids, matrix, glosses_per_cog, nexus_path)

    print(f"Writing summary:    {summary_path}")
    write_summary(taxa, char_ids, matrix, glosses_per_cog, summary_path)

    print(f"\nMatrix dimensions: {len(taxa)} taxa x {len(char_ids)} characters")
    print(f"NEXUS file ready for BEAST 2 / MrBayes input.")
    return taxa, char_ids, matrix, glosses_per_cog


if __name__ == "__main__":
    main()
